### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by carstenbauer** [JuliaPerf/LinuxPerf.jl#12]
`ioctl: Bad file descriptor`

https://github.com/JuliaPerf/LinuxPerf.jl/runs/2276809798?check_suite_focus=true#step:7:111

**Comment by tkf** [comment]
@vchuravy pointed out this in slack:

> We have to run this in our AWS instances because Github's own Azure instances don't provide virtualized hardware performance counters and thus don't support `rr` recording.
>
> --- [Implementing Pernosco Support For Github Actions](https://pernos.co/blog/github-actions/)

So, it looks like LinuxPerf.jl needs to run on a different platform like buildkite.
