### ISSUE TITLE
ioctl: Bad file descriptor

### ISSUE THREAD

**Issue by fcdimitr** [JuliaPerf/LinuxPerf.jl#16]
The `SystemError`

```
ERROR: SystemError: ioctl: Bad file descriptor
Stacktrace:
 [1] systemerror(p::Symbol, errno::Int32; extrainfo::Nothing)
   @ Base ./error.jl:168
 [2] #systemerror#62
   @ ./error.jl:167 [inlined]
 [3] systemerror
   @ ./error.jl:167 [inlined]
 [4] ioctl
   @ ~/.julia/packages/LinuxPerf/ZE1fQ/src/LinuxPerf.jl:331 [inlined]
 [5] reset!
   @ ~/.julia/packages/LinuxPerf/ZE1fQ/src/LinuxPerf.jl:337 [inlined]
 [6] LinuxPerf.EventGroup(types::Vector{LinuxPerf.EventType}; warn_unsupported::Bool, userspace_only::Bool, pinned::Bool, exclusive::Bool, pid::Int32)
   @ LinuxPerf ~/.julia/packages/LinuxPerf/ZE1fQ/src/LinuxPerf.jl:310
 [7] EventGroup
   @ ~/.julia/packages/LinuxPerf/ZE1fQ/src/LinuxPerf.jl:235 [inlined]
 [8] make_bench(x::Vector{Any})
   @ LinuxPerf ~/.julia/packages/LinuxPerf/ZE1fQ/src/LinuxPerf.jl:415
 [9] top-level scope
   @ ~/.julia/packages/LinuxPerf/ZE1fQ/src/LinuxPerf.jl:21
```

is thrown when trying to run the example shown in the `README.md`. I am running Ubuntu 16.04.5 LTS, with an AMD Ryzen CPU. I start `Julia` using `sudo`, to make sure it is not a permission issue.

Is there any known fixes for this error?

Many thanks in advance.

**Comment by topolarity** [comment]
This might be related to your `perf_event_paranoid` settings, which we now mention when this failure happens: https://github.com/JuliaPerf/LinuxPerf.jl/pull/40

**Comment by fcdimitr** [comment]
Thanks! Unfortunately, I don't have access to the same environment to replicate this problem. If you haven't seen the same issue from other sources, we can close it for now. If I encounter it again, I will re-open the issue or leave further comments.

**Comment by topolarity** [comment]
Sounds good, thanks @fcdimitr!
