### ISSUE TITLE
Does this only support x86_64

### ISSUE THREAD

**Issue by Zentrik** [JuliaPerf/LinuxPerf.jl#39]
It looks to me that syscall numbers differ on different platforms, so this code is only going to work on x86_64 as https://github.com/torvalds/linux/blob/v4.17/arch/x86/entry/syscalls/syscall_32.tbl#L17 says `perf_event_open` is 336 on i686
https://github.com/JuliaPerf/LinuxPerf.jl/blob/b7653aa80ce8e53c101157b592b80c6d2100c87e/src/LinuxPerf.jl#L158-L168

If this package only supports x86_64 I think it makes sense to add to the readme.

**Comment by vchuravy** [comment]
It should be easy enough to add the branches, but yes I think only x86_64 has ever been tested
