### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by chriselrod** [JuliaPerf/LinuxPerf.jl#8]
I've been on the master branch since the `@pstats` macro was merged on July 1st.

**Comment by crstnbr** [comment]
@vchuravy Any objections to tagging a new release? If not, I can take care of it.

**Comment by vchuravy** [comment]
@crstnbr please do!

**Comment by crstnbr** [comment]
Let me try to fix CI - I'll drop Travis and move to GitHub Actions - before making a new release.

(If I fail, I'll still tag a new release. After all we have a history here to create releases with failing CI 😆)

**Comment by crstnbr** [comment]
Done: https://github.com/JuliaRegistries/General/pull/33632. I made it a breaking release to be on the safe side.

(CI still failing because `perf` can't be accessed (`Permission denied`), see #9.)

**Comment by crstnbr** [comment]
@chriselrod Maybe you can/want to add a `@pstats` example to the README.md?
